# Generated by Django 3.2.5 on 2021-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_work',
            field=models.BooleanField(default=False, verbose_name='может использовать сервис'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждён сотрудником'),
        ),
    ]
