# Generated by Django 3.2.5 on 2021-08-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20210812_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_work',
        ),
    ]
