# Generated by Django 3.2.5 on 2021-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_remove_user_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32, verbose_name='токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время генерации')),
                ('claimed', models.BooleanField(default=False, verbose_name='использован')),
            ],
            options={
                'verbose_name': 'токен для регистрации',
                'verbose_name_plural': 'токены для регистрации',
            },
        ),
    ]
