# Generated by Django 3.2.5 on 2021-09-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0037_remove_container_sticker'),
        ('users_app', '0007_rename_claimed_registrationtoken_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='containers_app.building', verbose_name='здание'),
        ),
    ]
