# Generated by Django 3.2.5 on 2024-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0050_building_sticker_giver'),
        ('users_app', '0010_delete_registrationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='building',
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ManyToManyField(blank=True, to='containers_app.Building', verbose_name='здания'),
        ),
    ]
