# Generated by Django 3.2.5 on 2024-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_auto_20241107_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='MJMLTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Template Name')),
                ('mjml_content', models.TextField(verbose_name='MJML Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'MJML Template',
                'verbose_name_plural': 'MJML Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
