# Generated by Django 3.2.5 on 2021-07-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullContainersNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'оповещение о полных контейнерах',
                'verbose_name_plural': 'оповещения о полных контейнерах',
            },
        ),
        migrations.CreateModel(
            name='TakeoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='takeouts_app.fullcontainersnotification', verbose_name='оповещение')),
            ],
            options={
                'verbose_name': 'вынос',
                'verbose_name_plural': 'выносы',
            },
        ),
    ]
