# Generated by Django 3.2.5 on 2021-07-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullContainersNotification',
            new_name='EnoughFullContainersNotification',
        ),
        migrations.RemoveField(
            model_name='takeoutrequest',
            name='notification',
        ),
    ]
