# Generated by Django 3.2.5 on 2021-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0014_auto_20210719_1643'),
        ('takeouts_app', '0003_auto_20210715_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerstakeoutrequest',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время подтверждения'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='emptied_containers',
            field=models.ManyToManyField(related_name='takeout_confirmations', to='containers_app.Container', verbose_name='контейнеры подтверждённые пустыми'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='worker_info',
            field=models.CharField(blank=True, max_length=2048, verbose_name='информация о рабочем'),
        ),
        migrations.DeleteModel(
            name='ContainersTakeoutConfirmation',
        ),
    ]
