# Generated by Django 3.2.5 on 2021-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0005_tanktakeoutrequest_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanktakeoutrequest',
            name='confirmed_mass',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='подтверждённая масса вывоза в кг'),
        ),
    ]
