# Generated by Django 3.2.5 on 2021-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0006_tanktakeoutrequest_confirmed_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanktakeoutrequest',
            name='mass',
            field=models.PositiveSmallIntegerField(default=3000, verbose_name='масса вывоза в кг'),
            preserve_default=False,
        ),
    ]
