# Generated by Django 3.2.5 on 2021-07-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0014_auto_20210719_1643'),
        ('takeouts_app', '0008_remove_tanktakeoutrequest_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='containers_takeout_requests', to='containers_app.building', verbose_name='здание'),
            preserve_default=False,
        ),
    ]
