# Generated by Django 3.2.5 on 2021-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0009_containerstakeoutrequest_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'заготовитель',
                'verbose_name_plural': 'заготовители',
            },
        ),
    ]
