# Generated by Django 3.2.5 on 2021-07-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0019_container_building_part'),
        ('takeouts_app', '0010_takeoutcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoutCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'не больше N дней в офисе'), (2, 'не больше N дней в общественном месте'), (3, 'суммарная масса бумаги в корпусе не больше N кг'), (4, 'игнорировать первые N сообщенийо заполненности контейнера в общественном месте')], verbose_name='тип условия')),
                ('number', models.PositiveIntegerField(verbose_name='N')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_conditions', to='containers_app.building', verbose_name='здание')),
                ('building_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeout_conditions', to='containers_app.buildingpart', verbose_name='корпус здания')),
            ],
            options={
                'verbose_name': 'условие для сбора',
                'verbose_name_plural': 'условия для сбора',
            },
        ),
        migrations.AddConstraint(
            model_name='takeoutcondition',
            constraint=models.UniqueConstraint(fields=('building_part', 'type'), name='unique_condition_for_building'),
        ),
    ]
