# Generated by Django 3.2.5 on 2021-08-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0020_delete_takeoutconditionmet'),
        ('takeouts_app', '0012_auto_20210728_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='building_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers_takeout_requests', to='containers_app.buildingpart', verbose_name='корпус'),
        ),
    ]
