# Generated by Django 3.2.5 on 2021-08-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0017_alter_masstakeoutconditioncommit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerstakeoutrequest',
            options={'verbose_name': 'запрос сбора контейнеров', 'verbose_name_plural': 'запросы сбора контейнеров'},
        ),
    ]
