# Generated by Django 3.2.5 on 2021-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0023_remove_container_is_full'),
        ('takeouts_app', '0018_alter_containerstakeoutrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerstakeoutrequest',
            name='emptied_containers',
            field=models.ManyToManyField(blank=True, related_name='takeout_confirmations', to='containers_app.Container', verbose_name='контейнеры подтверждённые пустыми'),
        ),
    ]
