# Generated by Django 3.2.5 on 2021-09-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0037_remove_container_sticker'),
        ('takeouts_app', '0019_alter_containerstakeoutrequest_emptied_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTakeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=128, verbose_name='ФИО обратившегося сотрудника')),
                ('worker_phone', models.CharField(max_length=24, verbose_name='телефон сотрудника')),
                ('room', models.CharField(max_length=16, verbose_name='аудитория')),
                ('mass', models.CharField(max_length=64, verbose_name='масса сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_takeouts', to='containers_app.building', verbose_name='здание')),
            ],
            options={
                'verbose_name': 'сбор архива',
                'verbose_name_plural': 'сборы архива',
            },
        ),
    ]
