# Generated by Django 3.2.5 on 2021-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0020_archivetakeout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivetakeout',
            options={'verbose_name': 'сбор архива', 'verbose_name_plural': 'сборы архивов'},
        ),
        migrations.AlterField(
            model_name='archivetakeout',
            name='mass',
            field=models.PositiveIntegerField(verbose_name='масса'),
        ),
    ]
