# Generated by Django 3.2.5 on 2021-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0021_auto_20210905_1616'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='takeoutcondition',
            name='unique_condition_for_building',
        ),
        migrations.RemoveField(
            model_name='takeoutcondition',
            name='building_part',
        ),
        migrations.RemoveField(
            model_name='takeoutcondition',
            name='number',
        ),
        migrations.RemoveField(
            model_name='takeoutcondition',
            name='type',
        ),
        migrations.AddField(
            model_name='takeoutcondition',
            name='ignore_reports',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='кол-во первых сообщений, которые нужно игнорировать'),
        ),
        migrations.AddField(
            model_name='takeoutcondition',
            name='mass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальная суммарная масса бумаги'),
        ),
        migrations.AddField(
            model_name='takeoutcondition',
            name='office_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное кол-во дней в офисе полным'),
        ),
        migrations.AddField(
            model_name='takeoutcondition',
            name='public_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное кол-во дней в общ. месте полным'),
        ),
    ]
