# Generated by Django 3.2.5 on 2021-09-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0037_remove_container_sticker'),
        ('takeouts_app', '0022_auto_20210905_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutcondition',
            name='building_part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers_app.buildingpart', verbose_name='корпус здания'),
        ),
    ]
