# Generated by Django 3.2.5 on 2021-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0026_auto_20210906_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='archive_mass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='масса'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='archive_room',
            field=models.CharField(blank=True, max_length=16, verbose_name='аудитория'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='requesting_worker_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='ФИО обратившегося сотрудника (архив)'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='requesting_worker_phone',
            field=models.CharField(blank=True, max_length=24, verbose_name='телефон сотрудника (архив)'),
        ),
        migrations.DeleteModel(
            name='ArchiveTakeout',
        ),
    ]
