# Generated by Django 3.2.5 on 2021-09-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0028_auto_20210910_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerstakeoutrequest',
            options={'verbose_name': 'сбор контейнеров', 'verbose_name_plural': 'сборы контейнеров'},
        ),
        migrations.AlterModelOptions(
            name='tanktakeoutrequest',
            options={'verbose_name': 'вывоз бака', 'verbose_name_plural': 'вывозы баков'},
        ),
    ]
