# Generated by Django 3.2.5 on 2021-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0029_auto_20210922_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoutcondition',
            name='mass',
            field=models.IntegerField(blank=True, null=True, verbose_name='максимальная суммарная масса бумаги'),
        ),
        migrations.AlterField(
            model_name='takeoutcondition',
            name='office_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='максимальное кол-во дней в офисе полным'),
        ),
        migrations.AlterField(
            model_name='takeoutcondition',
            name='public_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='максимальное кол-во дней в общ. месте полным'),
        ),
    ]
