# Generated by Django 3.2.5 on 2021-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0049_building_detect_building_part'),
        ('takeouts_app', '0033_auto_20210928_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='already_empty_containers',
            field=models.ManyToManyField(blank=True, related_name='fake_takeout_requests', to='containers_app.Container', verbose_name='контейнеры, которые были пустыми'),
        ),
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='unavailable_containers',
            field=models.ManyToManyField(blank=True, related_name='unconfirmed_takeout_requests', to='containers_app.Container', verbose_name='недоступные контейнеры'),
        ),
    ]
