# Generated by Django 3.2.5 on 2021-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeouts_app', '0034_auto_20211013_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstakeoutrequest',
            name='archive_description',
            field=models.TextField(blank=True, verbose_name='описание для выноса архива'),
        ),
    ]
