# Generated by Django 3.1.12 on 2021-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False, verbose_name='заполнен')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
        ),
    ]
