# Generated by Django 3.1.12 on 2021-07-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2048, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'здание',
                'verbose_name_plural': 'здания',
            },
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'контейнер', 'verbose_name_plural': 'контейнеры'},
        ),
        migrations.AddField(
            model_name='container',
            name='building_part',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='container',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.CharField(default='asd', max_length=1024, verbose_name='аудитория/описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='containers_app.building', verbose_name='здание'),
        ),
    ]
