# Generated by Django 3.1.12 on 2021-07-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0002_auto_20210706_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='containers_app.building', verbose_name='здание'),
            preserve_default=False,
        ),
    ]
