# Generated by Django 3.2.5 on 2021-07-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0003_auto_20210706_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FullContainerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='первый раз получено')),
                ('count', models.SmallIntegerField(default=1, verbose_name='количество сообщений')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_reports', to='containers_app.container', verbose_name='контейнер')),
            ],
            options={
                'verbose_name': 'контейнер заполнен',
                'verbose_name_plural': 'контейнеры заполнены',
            },
        ),
    ]
