# Generated by Django 3.2.5 on 2021-07-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0005_fullcontainerreport_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullcontainerreport',
            name='notification',
        ),
    ]
