# Generated by Django 3.2.5 on 2021-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0006_remove_fullcontainerreport_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='нужно вынести бумагу'),
        ),
    ]
