# Generated by Django 3.2.5 on 2021-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0008_building_enough_full_containers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='sticker',
            field=models.ImageField(blank=True, upload_to='stickers/', verbose_name='стикер'),
        ),
    ]
