# Generated by Django 3.2.5 on 2021-07-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0009_container_sticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullcontainerreport',
            old_name='created_at',
            new_name='reported_full_at',
        ),
        migrations.RemoveField(
            model_name='building',
            name='enough_full_containers_count',
        ),
        migrations.RemoveField(
            model_name='building',
            name='is_full',
        ),
        migrations.AddField(
            model_name='fullcontainerreport',
            name='emptied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='контейнер вынесен'),
        ),
        migrations.CreateModel(
            name='EnoughFullContainersNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_containers_notifications', to='containers_app.building', verbose_name='здание')),
            ],
            options={
                'verbose_name': 'оповещение о полных контейнерах',
                'verbose_name_plural': 'оповещения о полных контейнерах',
            },
        ),
    ]
