# Generated by Django 3.2.5 on 2021-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0010_auto_20210715_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='находится в общественном месте'),
        ),
    ]
