# Generated by Django 3.2.5 on 2021-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0011_container_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='объём'),
            preserve_default=False,
        ),
    ]
