# Generated by Django 3.2.5 on 2021-07-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0013_container_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnoughFullContainersNotification',
            new_name='TakeoutConditionMet',
        ),
        migrations.AlterModelOptions(
            name='takeoutconditionmet',
            options={'verbose_name': 'выполнено условие для выноса', 'verbose_name_plural': 'выполнены условия для выноса'},
        ),
    ]
