# Generated by Django 3.2.5 on 2021-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0014_auto_20210719_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='почта (для связи)'),
        ),
        migrations.AddField(
            model_name='container',
            name='phone',
            field=models.CharField(blank=True, max_length=24, verbose_name='номер телефона (для связи)'),
        ),
    ]
