# Generated by Django 3.2.5 on 2021-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0015_auto_20210720_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='is_active',
        ),
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ожидает подключения'), (2, 'активный'), (3, 'не активный')], default=2, verbose_name='состояние'),
        ),
    ]
