# Generated by Django 3.2.5 on 2021-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0016_auto_20210720_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='email коменданта здания'),
            preserve_default=False,
        ),
    ]
