# Generated by Django 3.2.5 on 2021-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0017_building_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='building_part',
        ),
        migrations.CreateModel(
            name='BuildingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(verbose_name='номер корпуса')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_parts', to='containers_app.building', verbose_name='здание')),
            ],
            options={
                'verbose_name': 'корпус здания',
                'verbose_name_plural': 'корпусы зданий',
            },
        ),
    ]
