# Generated by Django 3.2.5 on 2021-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0018_auto_20210721_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='building_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='containers_app.buildingpart', verbose_name='корпус'),
        ),
    ]
