# Generated by Django 3.2.5 on 2021-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0020_delete_takeoutconditionmet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='email',
        ),
        migrations.AddField(
            model_name='building',
            name='containers_takeout_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email компании, выносящей баки'),
        ),
        migrations.AddField(
            model_name='building',
            name='itmo_worker_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email коменданта здания'),
        ),
    ]
