# Generated by Django 3.2.5 on 2021-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0021_auto_20210802_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='capacity',
        ),
        migrations.AddField(
            model_name='container',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экобокс'), (2, 'офисная урна'), (3, 'коробка из-под бумаги')], default=1, verbose_name='вид контейнера'),
            preserve_default=False,
        ),
    ]
