# Generated by Django 3.2.5 on 2021-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0022_auto_20210808_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='is_full',
        ),
    ]
