# Generated by Django 3.2.5 on 2021-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0023_remove_container_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='location',
        ),
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='container',
            name='room',
            field=models.CharField(blank=True, max_length=16, verbose_name='аудитория'),
        ),
    ]
