# Generated by Django 3.2.5 on 2021-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0024_auto_20210821_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='_full',
            field=models.BooleanField(default=False, verbose_name='полный (для сортировки)'),
        ),
    ]
