# Generated by Django 3.2.5 on 2021-08-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0025_container__full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='_full',
            new_name='_is_full',
        ),
    ]
