# Generated by Django 3.2.5 on 2021-08-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0026_rename__full_container__is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcontainerreport',
            name='by_staff',
            field=models.BooleanField(default=False, verbose_name='сотрудником'),
        ),
    ]
