# Generated by Django 3.2.5 on 2021-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0027_fullcontainerreport_by_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='itmo_worker_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='ФИО коменданта здания'),
        ),
    ]
