# Generated by Django 3.2.5 on 2021-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0028_building_itmo_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='containers_takeout_email',
        ),
        migrations.AddField(
            model_name='building',
            name='itmo_worker_phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='номер коменданта здания'),
        ),
    ]
