# Generated by Django 3.2.5 on 2021-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0029_auto_20210824_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='get_container_room',
            field=models.CharField(blank=True, max_length=64, verbose_name='аудитория, в которой можно получить контейнер'),
        ),
    ]
