# Generated by Django 3.2.5 on 2021-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0030_building_get_container_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='get_sticker_room',
            field=models.CharField(blank=True, max_length=64, verbose_name='аудитория, в которой можно получить стикер'),
        ),
    ]
