# Generated by Django 3.2.5 on 2021-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0031_building_get_sticker_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='created_at',
        ),
        migrations.AddField(
            model_name='container',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время активации'),
        ),
    ]
