# Generated by Django 3.2.5 on 2021-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0032_auto_20210825_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='avg_fill_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cреднее время заполнения контейнера'),
        ),
        migrations.AddField(
            model_name='container',
            name='avg_takeout_wait_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='среднее время ожидания выноса контейнера'),
        ),
    ]
