# Generated by Django 3.2.5 on 2021-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0034_auto_20210826_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='avg_fill_time',
            field=models.DurationField(blank=True, null=True, verbose_name='cреднее время заполнения контейнера'),
        ),
        migrations.AddField(
            model_name='container',
            name='avg_takeout_wait_time',
            field=models.DurationField(blank=True, null=True, verbose_name='среднее время ожидания выноса контейнера'),
        ),
    ]
