# Generated by Django 3.2.5 on 2021-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0035_auto_20210826_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='container',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экобокс'), (2, 'экобокс в общественном месте'), (3, 'коробка из-под бумаги')], verbose_name='вид контейнера'),
        ),
    ]
