# Generated by Django 3.2.5 on 2021-09-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0036_auto_20210901_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='sticker',
        ),
    ]
