# Generated by Django 3.2.5 on 2021-09-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0038_containeractivationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='itmo_worker_email',
        ),
        migrations.RemoveField(
            model_name='building',
            name='itmo_worker_name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='itmo_worker_phone',
        ),
    ]
