# Generated by Django 3.2.5 on 2021-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0039_auto_20210907_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32, verbose_name='токен')),
            ],
            options={
                'verbose_name': 'токен для email',
                'verbose_name_plural': 'токены для email',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='requested_activation',
            field=models.BooleanField(default=False, verbose_name='запрошена активация'),
        ),
        migrations.DeleteModel(
            name='ContainerActivationToken',
        ),
    ]
