# Generated by Django 3.2.5 on 2021-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0045_alter_container_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='использован'),
        ),
    ]
