# Generated by Django 3.2.5 on 2021-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0046_emailtoken_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcontainerreport',
            name='filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='заполнен в'),
        ),
    ]
