# Generated by Django 3.2.5 on 2021-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0047_fullcontainerreport_filled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpart',
            name='num',
            field=models.CharField(max_length=32, verbose_name='номер корпуса'),
        ),
        migrations.AlterField(
            model_name='container',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экобокс'), (2, 'контейнер в общественном месте'), (3, 'офисная урна')], verbose_name='вид контейнера'),
        ),
    ]
