# Generated by Django 3.2.5 on 2021-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0049_building_detect_building_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sticker_giver',
            field=models.CharField(blank=True, max_length=256, verbose_name='контакты человека, который выдаёт стикер'),
        ),
    ]
