# Generated by Django 3.2.5 on 2024-11-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers_app', '0050_building_sticker_giver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='containers_app.building', verbose_name='здание'),
        ),
    ]
